import { createHash, randomBytes } from 'node:crypto';
const RETS_VERSION = 'RETS/1.7.2';
const md5 = (value) => createHash('md5').update(value).digest('hex');
function parseDigestChallenge(header = '') { const values = {}; const source = String(header || '').replace(/^Digest\s+/i, ''); const pattern = /(\w+)=(?:"([^"]*)"|([^,\s]+))/g; let match; while ((match = pattern.exec(source))) values[match[1].toLowerCase()] = match[2] ?? match[3]; return values; }
function cookieValue(setCookie = '', name) { const match = setCookie.match(new RegExp('(?:^|[,;]\\s*)' + name + '=([^;,]+)', 'i')); return match?.[1] || ''; }
export class RetsProtocolError extends Error { constructor(code, { status, replyCode } = {}) { super(code); this.code = code; this.status = status; this.replyCode = replyCode; } }
function replyError(body) { const match = body.match(/<RETS\s+ReplyCode="([^"]+)"\s+ReplyText="([^"]*)"/i); if (match && match[1] !== '0' && match[1] !== '20201') return new RetsProtocolError('rets-rejection', { replyCode: Number(match[1]) }); return null; }
export class RetsSession {
 constructor({ loginUrl, username, password, userAgent, userAgentPassword, onStage } = {}) { this.loginUrl=loginUrl; this.username=username; this.password=password; this.userAgent=userAgent; this.userAgentPassword=userAgentPassword; this.origin=new URL(loginUrl).origin; this.challenge=null; this.sessionId=''; this.cookie=''; this.nonceCount=0; this.capabilities={}; this.onStage=typeof onStage === 'function' ? onStage : () => {}; }
 baseHeaders() { return {'User-Agent':this.userAgent,'RETS-Version':RETS_VERSION}; }
 authorization(url, method='GET') { const challenge=this.challenge; const uri=url.pathname + url.search; const nc=(++this.nonceCount).toString(16).padStart(8,'0'); const cnonce=randomBytes(12).toString('hex'); const qop=(challenge.qop || 'auth').split(',')[0].trim(); const ha1=md5(this.username + ':' + challenge.realm + ':' + this.password); const ha2=md5(method + ':' + uri); const result=md5(ha1 + ':' + challenge.nonce + ':' + nc + ':' + cnonce + ':' + qop + ':' + ha2); const parts=['username="' + this.username + '"','realm="' + challenge.realm + '"','nonce="' + challenge.nonce + '"','uri="' + uri + '"','response="' + result + '"','qop=' + qop,'nc=' + nc,'cnonce="' + cnonce + '"']; if (challenge.opaque) parts.push('opaque="' + challenge.opaque + '"'); return 'Digest ' + parts.join(', '); }
 uaAuthorization() { const a1=md5(this.userAgent + ':' + this.userAgentPassword); return 'Digest ' + md5(a1 + '::' + this.sessionId + ':' + RETS_VERSION); }
 async start() { this.onStage({stage:'challenge'}); const challengeResponse=await fetch(this.loginUrl,{headers:this.baseHeaders(),redirect:'manual',signal:AbortSignal.timeout(10000)}); const rawChallenge=challengeResponse.headers.get('www-authenticate'); this.challenge=parseDigestChallenge(rawChallenge); const setCookies=challengeResponse.headers.getSetCookie?.() || [challengeResponse.headers.get('set-cookie') || '']; this.cookie=setCookies.map((value)=>value.split(';')[0]).filter(Boolean).join('; '); this.sessionId=cookieValue(this.cookie,'RETS-Session-ID'); this.onStage({stage:'challenge',hasDigestChallenge:Boolean(this.challenge.nonce),hasSessionCookie:Boolean(this.sessionId),upstreamStatus:challengeResponse.status,mime:challengeResponse.headers.get('content-type')}); if (challengeResponse.status !== 401) throw new RetsProtocolError(challengeResponse.status >= 300 && challengeResponse.status < 400 ? 'redirect' : 'upstream-http',{status:challengeResponse.status}); if (!this.challenge.nonce) throw new RetsProtocolError('challenge-missing',{status:challengeResponse.status}); if (!this.challenge.realm || !this.challenge.qop) throw new RetsProtocolError('challenge-malformed',{status:challengeResponse.status}); if (!this.sessionId) throw new RetsProtocolError('session-cookie-missing',{status:challengeResponse.status}); this.onStage({stage:'authenticated-login'}); const response=await this.request(this.loginUrl); const body=await response.text(); this.onStage({stage:'authenticated-login',upstreamStatus:response.status,mime:response.headers.get('content-type')}); const error=replyError(body); if (error) throw error; for (const line of body.split(/\r?\n/)) { const match=line.match(/^([A-Za-z]+)=(.+)$/); if (match) this.capabilities[match[1]]=match[2].trim(); } this.onStage({stage:'capabilities',hasSearchCapability:Boolean(this.capabilities.Search)}); if (!this.capabilities.Search) throw new RetsProtocolError('capability-missing'); return this; }
 async request(target,params={}) { const url=new URL(target,this.origin); if (url.origin !== this.origin) throw new RetsProtocolError('capability-origin'); for (const [key,value] of Object.entries(params)) if (value !== undefined && value !== null && value !== '') url.searchParams.set(key,String(value)); const response=await fetch(url,{headers:{...this.baseHeaders(),Authorization:this.authorization(url),Cookie:this.cookie,'RETS-UA-Authorization':this.uaAuthorization()},redirect:'manual',signal:AbortSignal.timeout(10000)}); if (response.status === 401) throw new RetsProtocolError('authenticated-rejection',{status:response.status}); if (response.status >=300 && response.status <400) throw new RetsProtocolError('redirect',{status:response.status}); if (response.status <200 || response.status >=300) throw new RetsProtocolError('upstream-http',{status:response.status}); return response; }
 async text(capability,params={}) { if (!this.capabilities[capability]) throw new RetsProtocolError('capability-missing'); const response=await this.request(this.capabilities[capability],params); const body=Buffer.from(await response.arrayBuffer()).toString('latin1'); const error=replyError(body); if (error) throw error; if (!/<RETS\b/i.test(body)) throw new RetsProtocolError('non-rets-response',{status:response.status}); return body; }
 async close() { if (!this.capabilities.Logout) return; try { await this.request(this.capabilities.Logout); } catch {} }
}
export function parseCompact(body) { const columnsMatch=body.match(/<COLUMNS>\s*([\s\S]*?)\s*<\/COLUMNS>/i); if (!columnsMatch) return []; const columns=columnsMatch[1].split('\t').filter(Boolean); return [...body.matchAll(/<DATA>\s*([\s\S]*?)\s*<\/DATA>/gi)].map((match)=>{const values=match[1].split('\t'); if(values[0]==='') values.shift(); if(values.at(-1)==='') values.pop(); return Object.fromEntries(columns.map((column,index)=>[column,decodeEntities(values[index] || '')]));}); }
function decodeEntities(value) { return value.replaceAll('&apos;',"'").replaceAll('&quot;','"').replaceAll('&amp;','&').replaceAll('&lt;','<').replaceAll('&gt;','>'); }
export function retsConfigFromEnv() { const config={loginUrl:process.env.GSMLS_RETS_LOGIN_URL,username:process.env.GSMLS_RETS_USERNAME,password:process.env.GSMLS_RETS_PASSWORD,userAgent:process.env.GSMLS_RETS_USER_AGENT,userAgentPassword:process.env.GSMLS_RETS_USER_AGENT_PASSWORD}; if (Object.values(config).some((value)=>typeof value !== 'string' || !value.trim() || value !== value.trim())) throw new RetsProtocolError('config'); return config; }
