import { randomUUID } from 'node:crypto';
import sharp from 'sharp';
import { parseCompact, RetsSession, retsConfigFromEnv } from '../_lib/rets.js';
export const config = { maxDuration: 30 };
const counties = ['Bergen','Essex','Hudson','Passaic','Monmouth','Ocean'];
const allowedCounties = new Set(counties), allowedPropertyTypes = new Set(['Single Family','Condo','Townhome']), allowedSorts = new Set(['newest','price-asc','price-desc']), allowedMarkets = new Set(['buy','rent']);
function numberParam(value, minimum = 0) { if (value === null || value === '') return null; const parsed = Number(value); return Number.isFinite(parsed) && parsed >= minimum ? parsed : null; }
function dmqlValue(value) { return String(value).replace(/[^a-zA-Z0-9 .'-]/g, '').slice(0, 60); }
function propertyType(row) { const type = row.SUBPROPTYPE || 'Single Family'; return /condo/i.test(type) ? 'Condo' : /town/i.test(type) ? 'Townhome' : 'Single Family'; }
function mapListing(row, market) { const street = [row.STREETNUMDISPLAY,row.STREETNAME].filter(Boolean).join(' '); return { id:row.LISTINGID, mlsNumber:row.LISTINGID, title:street || row.CITY + ' home', city:row.CITY, county:row.COUNTY, state:'NJ', postalCode:row.POSTALCODE, price:Number(row.LISTPRICE || row.RENTPRICE || 0), beds:Number(row.BEDS || 0), baths:Number(row.BATHS || 0), propertyType:propertyType(row), market, status:row.LISTINGSTATUS, image:'', brokerName:row.LISTOFFICENAME, brokerContact:'', isIdxListing:String(row.LISTOFFICEID || '') !== '5049', updatedAt:row.LASTMODIFIED, details:{'MLS number':row.LISTINGID,ZIP:row.POSTALCODE} }; }function errorClass(error) { if (typeof error?.code === 'string') return error.code; if (error?.name === 'AbortError' || error?.name === 'TimeoutError') return 'timeout'; const text=String(error?.message || ''); if (text.includes('feed settings')) return 'configuration'; if (text.includes('did not start')) return 'initial-session'; if (text.includes('rejected')) return 'authenticated-rejection'; if (text.includes('GSMLS returned')) return 'rets-rejection'; return 'unknown'; }function replyCode(error) { if (Number.isInteger(error?.replyCode)) return error.replyCode; const match=String(error?.message || '').match(/GSMLS returned (\d{1,5})/); return match ? Number(match[1]) : undefined; }
function safeLog(values) { const entry={event:'idx_rets',timestamp:new Date().toISOString(),requestId:values.requestId,environment:process.env.VERCEL_ENV || 'local',deployment:process.env.VERCEL_DEPLOYMENT_ID,stage:values.stage,elapsedMs:values.elapsedMs,upstreamStatus:Number.isInteger(values.upstreamStatus) ? values.upstreamStatus : undefined,retsReplyCode:values.retsReplyCode,errorClass:values.errorClass}; console.error(JSON.stringify(Object.fromEntries(Object.entries(entry).filter(([,value]) => value !== undefined)))); }
async function addPhoto(session, listing) { try { const response=await session.request(session.capabilities.GetObject,{Resource:'PROPERTY',Type:'Photo',ID:listing.mlsNumber + ':0',Location:0}); if (!response.headers.get('content-type')?.includes('image/')) return listing; const source=Buffer.from(await response.arrayBuffer()); const image=await sharp(source).resize(900,600,{fit:'cover'}).jpeg({quality:72}).toBuffer(); return {...listing,image:'data:image/jpeg;base64,' + image.toString('base64')}; } catch { return listing; } }
export default async function handler(request,response) {
 if (request.method !== 'GET') { response.setHeader('Allow','GET'); return response.status(405).json({error:'Method not allowed.'}); }
 const url=new URL(request.url,'https://' + (request.headers.host || 'localhost')); const location=dmqlValue((url.searchParams.get('location') || '').trim()).toLowerCase(); const countyValue=url.searchParams.get('county') || '', typeValue=url.searchParams.get('propertyType') || '', sortValue=url.searchParams.get('sort') || 'newest', marketValue=url.searchParams.get('market') || 'buy'; const county=allowedCounties.has(countyValue) ? countyValue : '', requestedType=allowedPropertyTypes.has(typeValue) ? typeValue : '', sort=allowedSorts.has(sortValue) ? sortValue : 'newest', market=allowedMarkets.has(marketValue) ? marketValue : 'buy', priceField=market === 'rent' ? 'RENTPRICE' : 'LISTPRICE'; const featured=url.searchParams.get('featured') === '1', days=Math.min(numberParam(url.searchParams.get('days'),1) || 7,14), limit=Math.min(numberParam(url.searchParams.get('limit'),1) || 6,12), minPrice=numberParam(url.searchParams.get('minPrice')), maxPrice=numberParam(url.searchParams.get('maxPrice')), beds=numberParam(url.searchParams.get('beds')), baths=numberParam(url.searchParams.get('baths'));
 const terms=['(LISTINGSTATUS=A)','(COUNTY=' + (county || counties.join(',')) + ')']; if (location) terms.push(/^\d{5}$/.test(location) ? '(POSTALCODE=' + location + '*)' : '(CITY=*' + location + '*)'); if (minPrice && maxPrice) terms.push('(' + priceField + '=' + minPrice + '-' + maxPrice + ')'); else if (minPrice) terms.push('(' + priceField + '=' + minPrice + '+)'); else if (maxPrice) terms.push('(' + priceField + '=' + maxPrice + '-)'); if (beds) terms.push('(BEDS=' + beds + '+)'); if (baths) terms.push('(BATHS=' + baths + '+)');
 const requestId=randomUUID(), started=Date.now(); let stage='configuration', session;
 try { session=new RetsSession(retsConfigFromEnv()); stage='session-start'; await session.start(); const options={SearchType:'PROPERTY',Class:market === 'rent' ? 'RNT' : 'RES',Query:terms.join(','),QueryType:'DMQL2',Count:1,Format:'COMPACT-DECODED',Limit:limit,StandardNames:0}; options.Select='LISTINGID,LISTINGSTATUS,' + priceField + ',STREETNUMDISPLAY,STREETNAME,CITY,COUNTY,POSTALCODE,BEDS,BATHS,SUBPROPTYPE,LISTOFFICEID,LISTOFFICENAME,LASTMODIFIED'; stage='search'; const body=await session.text('Search',options); stage='compact-parsing'; let listings=parseCompact(body).map((row)=>mapListing(row,market)).filter((listing)=>{const matchesLocation=!location || [listing.title,listing.city,listing.postalCode].some((value)=>String(value || '').toLowerCase().includes(location)); const matchesFeaturedWindow=!featured || new Date(listing.updatedAt).getTime() >= Date.now() - days * 86400000; return matchesLocation && matchesFeaturedWindow && (!requestedType || listing.propertyType === requestedType);}); if (sort === 'price-asc') listings.sort((a,b)=>a.price-b.price); else if (sort === 'price-desc') listings.sort((a,b)=>b.price-a.price); else listings.sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)); listings=listings.slice(0,limit); for (let i=0;i<listings.length;i+=1) { stage='photo-resize'; listings[i]=await addPhoto(session,listings[i]); } response.setHeader('Cache-Control','public, s-maxage=300, stale-while-revalidate=600'); return response.status(200).json({listings}); }
 catch(error) { safeLog({requestId,stage,elapsedMs:Date.now()-started,upstreamStatus:error?.status,retsReplyCode:replyCode(error),errorClass:errorClass(error)}); return response.status(502).json({error:'Live home search could not load. Please try again.',requestId}); }
 finally { if (session) await session.close(); }
}
